root = "."      # The root directory of the project 
tmp_dir = "tmp" # The temporary directory where air will stire uts temporary files 

[build] # the build configuration 
bin = "main" # the name of the binary file to be generated after building the project 
cmd = "go build -o {{.Output}} {{.Input}}" # The command to build project 
exclude = [
    "tmp/*",
    "client/*",
] # Specifies the directories to be excluded from monitoring for changes 
include = [
    "**/*.go",
] #Specifies the file patterns to be included for monitoring.
ignore = [
    "tmp/*",
] #Specifies the file or directories to be ignored when triggering a build.
